repos:
  - repo: local
    hooks:
      - id: test
        name: Run make test
        entry: make test
        language: system
        pass_filenames: false
      - id: check
        name: Run make check
        entry: make check
        language: system
        pass_filenames: false
