receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
        - job_name: synthia
          scrape_interval: 15s
          static_configs:
            - targets:
                - synthia:8003

processors:
  transform/logs:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(attributes["trace_id"], trace_id.string)
          - set(attributes["span_id"], span_id.string)

exporters:
  otlp:
    endpoint: host.docker.internal:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - otlp

    metrics:
      receivers:
        - otlp
        - prometheus
      exporters:
        - otlp

    logs:
      receivers:
        - otlp
      processors:
        - transform/logs
      exporters:
        - otlp
