[project]
name = "synthia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.119.0",
    "loguru>=0.7.3",
    "python-dotenv>=1.1.1",
    "python-telegram-bot>=22.5",
]

[tool.ruff]
target-version = "py313"
line-length = 120

[dependency-groups]
dev = [
    "pytest-testmon>=2.1.3",
    "ruff>=0.14.0",
    "ty>=0.0.1a22",
]

# [tool.hatch.build.targets.wheel]
# packages = ["synthia"]